### DISCUSSION TITLE
Get Responses In JSON Format?

### DISCUSSION THREAD

**Discussion by Grems0203** [tillsteinbach/CarConnectivity#69] [Q&A] [answered]
Hey!
Is there an easy way toget the `print(garage.get_vehicle("xyz")` response as a JSON object rather than a text blob?
It would be easier to work with for future automations.
For example, for `vehicle.drives`, it gives the following output:
```
primary:
        level: 63.0%
        range: 433.0km
        type: electric
total_range: 433.0km
```
I cant access each of those values individually aside from `total_range` from what i can tell.
It would be good if i could do something like:
`print(drives['primary']['level'])`
