### ISSUE TITLE
Error importing Skoda cars

### ISSUE THREAD

**Issue by cimchd** [tillsteinbach/CarConnectivity#33]
I have an error with an Skoda account with 5 cars in the garage. I think it's probably not really an error but I am missing an error message that tells me what is wrong. Here's a screenshot of the error messages in Python:

![Image](https://github.com/user-attachments/assets/7e217c7d-58b2-4b25-9250-1904a57e9149)

Anyone ideas what could be wrong?

With my other Skoda account containing 2 cars I have no problem with the same code.

**Comment by tillsteinbach** [comment]
Wow! 5 cars! Power user!
Can you send me more of the log?

**Comment by cimchd** [comment]
It's a company account. We use your library to get an overview of the battery levels of our electric cars.

I don't know how much more you need. Probably this logs show the problem:
```
2025-03-20 22:23:44 2025-03-20T21:23:44+0000:urllib3.connectionpool:DEBUG:connectionpool:https://mysmob.api.connect.skoda-auto.cz:443 "GET /api/v2/vehicle-status/XXXXXXXXXXXXXXXXX/driving-range HTTP/1.1" 500 21
2025-03-20 22:23:44 2025-03-20T21:23:44+0000:urllib3.util.retry:DEBUG:retry:Incremented Retry for (url='/api/v2/vehicle-status/XXXXXXXXXXXXXXXXX/driving-range'): BlacklistRetry(total=2, connect=3, read=3, redirect=None, status=2)
2025-03-20 22:23:44 2025-03-20T21:23:44+0000:urllib3.connectionpool:DEBUG:connectionpool:Retry: /api/v2/vehicle-status/XXXXXXXXXXXXXXXXX/driving-range
2025-03-20 22:23:44 2025-03-20T21:23:44+0000:urllib3.connectionpool:DEBUG:connectionpool:https://mysmob.api.connect.skoda-auto.cz:443 "GET /api/v2/vehicle-status/XXXXXXXXXXXXXXXXX/driving-range HTTP/1.1" 500 21
2025-03-20 22:23:44 2025-03-20T21:23:44+0000:urllib3.util.retry:DEBUG:retry:Incremented Retry for (url='/api/v2/vehicle-status/XXXXXXXXXXXXXXXXX/driving-range'): BlacklistRetry(total=1, connect=3, read=3, redirect=None, status=1)
2025-03-20 22:23:44 2025-03-20T21:23:44+0000:urllib3.connectionpool:DEBUG:connectionpool:Retry: /api/v2/vehicle-status/XXXXXXXXXXXXXXXXX/driving-range
2025-03-20 22:23:44 2025-03-20T21:23:44+0000:urllib3.connectionpool:DEBUG:connectionpool:https://mysmob.api.connect.skoda-auto.cz:443 "GET /api/v2/vehicle-status/XXXXXXXXXXXXXXXXX/driving-range HTTP/1.1" 500 21
2025-03-20 22:23:44 2025-03-20T21:23:44+0000:urllib3.util.retry:DEBUG:retry:Incremented Retry for (url='/api/v2/vehicle-status/XXXXXXXXXXXXXXXXX/driving-range'): BlacklistRetry(total=0, connect=3, read=3, redirect=None, status=0)
2025-03-20 22:23:45 2025-03-20T21:23:45+0000:urllib3.connectionpool:DEBUG:connectionpool:Retry: /api/v2/vehicle-status/XXXXXXXXXXXXXXXXX/driving-range
2025-03-20 22:23:45 2025-03-20T21:23:45+0000:urllib3.connectionpool:DEBUG:connectionpool:https://mysmob.api.connect.skoda-auto.cz:443 "GET /api/v2/vehicle-status/XXXXXXXXXXXXXXXXX/driving-range HTTP/1.1" 500 21
```
I can provide you the whole log via email, if you need the real values for the accounts and vin numbers.

**Comment by tillsteinbach** [comment]
As a temporary workaround you could catch the retrieval error with a try/except block. Is it always the same car that throws the 500? is that a special car? Or maybe privacy settings set?

**Comment by tillsteinbach** [comment]
No, if it is a old car that is probably the reason. I would not follow that up if you can work around it for now.

**Comment by cimchd** [comment]
Ok, I deleted it

**Comment by cimchd** [comment]
Unfortunately it seems that in the `fetch_all()` function when the error occurs it does not continue with the other cars. `get_garage()` only returns the cars before the error occured. In my case the two cars from the other account do not get imported at all.

**Comment by tillsteinbach** [comment]
Yes, could do that, but I would rather prefer to catch the error right away. Would be interesting to see what the difference is between the cars having the error and the cars not having the error. When you print the car that throws the error, what capabilities does it have?

**Comment by cimchd** [comment]
This is what `print(vehicle)` prints out:
```
capabilities:
        ACCESS:
                id: ACCESS
                status: [<Status.UNKNOWN: 0>, <Status.LICENSE_EXPIRED: 2002>]
        ACCIDENT_DAMAGE_MANAGEMENT:
                id: ACCIDENT_DAMAGE_MANAGEMENT
                status: []
        AIR_CONDITIONING:
                id: AIR_CONDITIONING
                status: [<Status.UNKNOWN: 0>, <Status.LICENSE_EXPIRED: 2002>]
        AIR_CONDITIONING_HEATING_SOURCE_ELECTRIC:
                id: AIR_CONDITIONING_HEATING_SOURCE_ELECTRIC
                status: []
        AIR_CONDITIONING_SAVE_AND_ACTIVATE:
                id: AIR_CONDITIONING_SAVE_AND_ACTIVATE
                status: []
        AUTOMATION:
                id: AUTOMATION
                status: [<Status.UNKNOWN: 0>, <Status.LICENSE_EXPIRED: 2002>]
        CARE_AND_INSURANCE:
                id: CARE_AND_INSURANCE
                status: []
        CHARGING:
                id: CHARGING
                status: [<Status.UNKNOWN: 0>, <Status.LICENSE_EXPIRED: 2002>]
        CHARGING_MQB:
                id: CHARGING_MQB
                status: []
        CUBIC:
                id: CUBIC
                status: []
        DEALER_APPOINTMENT:
                id: DEALER_APPOINTMENT
                status: []
        DEPARTURE_TIMERS:
                id: DEPARTURE_TIMERS
                status: [<Status.UNKNOWN: 0>, <Status.LICENSE_EXPIRED: 2002>]
        DESTINATIONS:
                id: DESTINATIONS
                status: [<Status.UNKNOWN: 0>]
        DIGICERT:
                id: DIGICERT
                status: [<Status.UNKNOWN: 0>, <Status.LICENSE_EXPIRED: 2002>]
        DRIVING_SCORE:
                id: DRIVING_SCORE
                status: []
        FLEET_SUPPORTED:
                id: FLEET_SUPPORTED
                status: []
        FUEL_STATUS:
                id: FUEL_STATUS
                status: [<Status.UNKNOWN: 0>, <Status.LICENSE_EXPIRED: 2002>]
        GEO_FENCE:
                id: GEO_FENCE
                status: [<Status.UNKNOWN: 0>, <Status.LICENSE_EXPIRED: 2002>]
        HONK_AND_FLASH:
                id: HONK_AND_FLASH
                status: [<Status.UNKNOWN: 0>, <Status.LICENSE_EXPIRED: 2002>]
        MEASUREMENTS:
                id: MEASUREMENTS
                status: [<Status.UNKNOWN: 0>, <Status.LICENSE_EXPIRED: 2002>]
        MISUSE_PROTECTION:
                id: MISUSE_PROTECTION
                status: []
        ONLINE_SPEECH_GPS:
                id: ONLINE_SPEECH_GPS
                status: []
        OUTSIDE_TEMPERATURE:
                id: OUTSIDE_TEMPERATURE
                status: []
        PARKING_POSITION:
                id: PARKING_POSITION
                status: [<Status.UNKNOWN: 0>, <Status.LICENSE_EXPIRED: 2002>]
        PAY_TO_FUEL:
                id: PAY_TO_FUEL
                status: [<Status.UNKNOWN: 0>, <Status.LICENSE_EXPIRED: 2002>]
        PAY_TO_PARK:
                id: PAY_TO_PARK
                status: [<Status.UNKNOWN: 0>, <Status.LICENSE_EXPIRED: 2002>]
        POWERPASS_TARIFFS:
                id: POWERPASS_TARIFFS
                status: []
        ROADSIDE_ASSISTANT:
                id: ROADSIDE_ASSISTANT
                status: []
        ROUTE_IMPORT:
                id: ROUTE_IMPORT
                status: []
        SERVICE_PARTNER:
                id: SERVICE_PARTNER
                status: []
        SPEED_ALERT:
                id: SPEED_ALERT
                status: [<Status.UNKNOWN: 0>, <Status.LICENSE_EXPIRED: 2002>]
        STATE:
                id: STATE
                status: [<Status.UNKNOWN: 0>, <Status.LICENSE_EXPIRED: 2002>]
        SUBSCRIPTIONS:
                id: SUBSCRIPTIONS
                status: []
        TRIP_STATISTICS:
                id: TRIP_STATISTICS
                status: [<Status.UNKNOWN: 0>, <Status.LICENSE_EXPIRED: 2002>]
        VEHICLE_HEALTH_INSPECTION:
                id: VEHICLE_HEALTH_INSPECTION
                status: [<Status.UNKNOWN: 0>, <Status.LICENSE_EXPIRED: 2002>]
        VEHICLE_HEALTH_WARNINGS:
                id: VEHICLE_HEALTH_WARNINGS
                status: []
        VEHICLE_WAKE_UP:
                id: VEHICLE_WAKE_UP
                status: [<Status.UNKNOWN: 0>, <Status.LICENSE_EXPIRED: 2002>]
        WARNING_LIGHTS:
                id: WARNING_LIGHTS
                status: [<Status.UNKNOWN: 0>, <Status.LICENSE_EXPIRED: 2002>]
        WINDOW_HEATING:
                id: WINDOW_HEATING
                status: []
doors:
        lock_state: unknown lock state
        open_state: unknown open state
lights:
        light_state: off
manufacturer: Škoda
model: Octavia
name: XXXXXXX
vin: XXXXXXXXXXXXXXXXXX
windows:
        open_state: unknown open state
```
